### ISSUE TITLE
doesn't compile on qt6

### ISSUE THREAD

**Issue by AstonishedByTheLackOfCake** [chifandeyu/FramelessWnd#1]
I'm not sure what changes you made here, compared to dfct's TrueFramelessWindow, but this also straight up won't compile :/

**Comment by chifandeyu** [comment]
> I'm not sure what changes you made here, compared to dfct's TrueFramelessWindow, but this also straight up won't compile :/

I haven't tried it on Qt6 yet. I can compile and run use Qt5.12.5+vs2017. When I have time I will try to compile on Qt6.

**Comment by chifandeyu** [comment]
New code has fixed this issue.
